backend:
  name: git-gateway
  branch: main # Branch to update (main for new repos)

media_folder: "static/img" # Media files will be stored in the repo under static/img
public_folder: "/img"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
